version: '2'
linters:
  default: none
  enable:
    - err113
    - errcheck
    - forcetypeassert
    - gocognit
    - godot
    - govet
    - ineffassign
    - makezero
    - misspell
    - mnd
    - nakedret
    - nilerr
    - nlreturn
    - nolintlint
    - paralleltest
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    errcheck:
      exclude-functions:
        - github.com/hashicorp/terraform-plugin-testing/helper/schema:ForceNew|Set
        - fmt:.*
        - io:Close
    govet:
      enable:
        - fieldalignment
        - shadow
    misspell:
      ignore-rules:
        - intial
    mnd:
      checks:
        - argument
      ignored-functions:
        - make
        - strconv.FormatFloat
        - strconv.FormatInt
        - strconv.ParseFloat
        - strconv.ParseInt
        - strings.SplitN
        - int64validator.OneOf
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-no-explanation:
        - unparam
        - mnd
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - err113
          - funlen
          - unparam
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
