---
version: "3.9"
services:
  sonarr:
    image: ghcr.io/hotio/sonarr:release-4.0.20.3014@sha256:afc94d6134d3e21162bc86b82afee332c7555bedf4a29b710edcd794c9c38e1d
    container_name: sonarr
    depends_on:
      - transmission
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ./test.sh:/scripts/test.sh
      - ./config.xml:/config/config.xml
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989/system/status"]
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    ports:
      - 9091:9091
